### ISSUE TITLE
Warnings without line numbers

### ISSUE THREAD

**Issue by najamelan** [taiki-e/pin-project#104]
This is like a rustc bug, but I never saw this before using this crate, so I thought I'd report it here, since you know the ins of pin_project better. I haven't reported on rust repo for now.

```rust
#[ project ]
//
fn poll_ready( mut self: Pin<&mut Self>, cx: &mut Context<'_> ) -> Poll<Result<(), Self::Error>>
{
	#[ project ]
	//
	match self.project()
	{
		Sender::Bounded  { tx, .. } => tx.poll_ready( cx ).map_err( Into::into ),
		Sender::Unbounded{ tx, .. } => tx.poll_ready( cx ).map_err( Into::into ),
	}
}
```

Note the unnecessary mut before self. The warning is:
```shell
   Compiling pharos v0.2.2 (/pharos)
warning: variable does not need to be mutable
  |
  = note: `#[warn(unused_mut)]` on by default
```

No file, no line number, pretty obscure.

**Comment by taiki-e** [comment]
Thanks for the reporting. If I understand correctly, (as mentioned in #63) this is a rustc issue (rust-lang/rust#43081) and cannot be fixed on the proc-macro side.

**Comment by taiki-e** [comment]
However, if you use `#[project]` at the position of the function, `#[project]` should basically report a decent error, so I feel this is a bit odd. Is there a complete example of this?

**Comment by najamelan** [comment]
Taiki Endo:
> However, if you use `#[project]` at the position of the function, `#[project]` should basically report a decent error, so I feel this is a bit odd. Is there a complete example of this?
> 

This was basically just a stream impl with a redundant mut. I will push a commit online so you can reproduce.

**Comment by najamelan** [comment]
hmm,

now with the latest version of my code the warning is correct. I didn't update the compiler, so some things must have been interfering with one another.

Did a checkout of my code from yesterday and still can't reproduce. I have no idea what's going on. Sorry for the noise. I suppose we can close this.
