### ISSUE TITLE
#![feature(overlapping_marker_traits)] breaks the guarantee for Unpin provided by pin-project

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/pin-project#105]
UPDATE2(2020/01/27):

This will be fixed in rust-lang/rust#68544

---

UPDATE(2019/09/26):

`overlapping_marker_traits` is replaced with [marker_trait_attr](https://doc.rust-lang.org/nightly/unstable-book/language-features/marker-trait-attr.html).
`marker_trait_attr` doesn't seem to break the guarantee (added test in #110). So, once `overlapping_marker_traits` is removed, close this issue.

---

pin-project provides an appropriate `Unpin` implementation by default. Since overlapping implementations are prohibited, this ensures that users cannot add inappropriate `Unpin` implementations.

However, currently, this guarantee can be broken by enabling `#[feature(overlapping_marker_traits)]`: [playground](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=a4a94d17a6acc0f58e446a5f7b8f82bc)

@cramertj has already pointed out this in https://github.com/rust-lang/rust/issues/29864#issuecomment-409398581. 
~~And it seems that it is planned to make `#[feature(overlapping_marker_traits)]` available only with explicitly allowed traits, but it doesn't seem to be fully implemented yet.~~

---

Thanks to @RalfJung for [pointing out the interaction with this feature.](https://github.com/taiki-e/pin-project/pull/18#issuecomment-515780620)

**Comment by scottmcm** [comment]
The gate for the new behavior is https://doc.rust-lang.org/nightly/unstable-book/language-features/marker-trait-attr.html -- it was implemented in parallel without removing the old feature.

**Comment by taiki-e** [comment]
@scottmcm Thanks! I think I missed it.

However, even if it is deprecated, it breaks soundness, so I believe that it makes sense to leave this issue open until the feature is removed.

**Comment by taiki-e** [comment]
This will be fixed in https://github.com/rust-lang/rust/pull/68544 (Thanks @Aaron1011!)

**Comment by Aaron1011** [comment]
Now that https://github.com/rust-lang/rust/pull/68544 has been merged, I believe that this can be closed.
