### ISSUE TITLE
#[pinned_drop] is a silent no-op if (PinnedDrop) isn't added to #[pin_project]

### ISSUE THREAD

**Issue by sfackler** [taiki-e/pin-project#179]
If you take the `#[pinned_drop]` example and remove the argument to `#[pin_project]`, it compiles without warnings but doesn't actually run the PinnedDrop impl when dropping: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=a156327aa5ce88e290d1038cdff9df12

It'd be nice if that somehow caused a compilation error!

**Comment by taiki-e** [comment]
Published 0.4.8 which fixes this issue.

**Comment by sfackler** [comment]
Thanks!
