### ISSUE TITLE
Deprecate #[project] attributes in favor of the naming of projected-type

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/pin-project#225]
The naming of projected-type added in #202 is more powerful than `project*` attributes and the implementation is also very simple.

There some reasons for removing `project*` attributes in favor of the naming of projected-type:
* `project*` attributes aren't really available everywhere, and there are some unsupported cases (e.g., https://github.com/taiki-e/pin-project/issues/124#issuecomment-625764817).
* Each projection method requires a separate `project*` attribute.
* Having multiple ways to do the same is a bit confusing.
* We can avoid some problems (the implementation complexity and poor testing due to it) made that caused regressions like #206/hyperium/hyper#2199.
* Compatible with pin-project-lite. pin-project-lite may be able to support naming in the future (especially required if it supports enums).

That said, it may be tedious to name each time...

**Comment by Aaron1011** [comment]
I'm in favor of this - I think it's nice to only require using macros at the definition site.

**Comment by taiki-e** [comment]
I'll do this next week.

**Comment by taiki-e** [comment]
Also, in the future (when project attribute removed), we can reduce generated code by skips unnamed projection types and methods when pin_project used on enums.
