### ISSUE TITLE
"Code like this will be generated" is outdated?

### ISSUE THREAD

**Issue by RalfJung** [taiki-e/pin-project#25]
[This](https://github.com/taiki-e/pin-project/blob/master/doc/struct-example-1.md) does not show anything `Drop`-related so it likely does not reflect the current expansion.

**Comment by RalfJung** [comment]
The same example is also embedded [here](https://github.com/taiki-e/pin-project/blob/ce85621668e78f09e8b4388006c44033d11b4667/pin-project/src/lib.rs#L31).

**Comment by taiki-e** [comment]
Yeah, we need to update them.

**Comment by taiki-e** [comment]
FWIW, we currently have [tests for checking the code generated by macros](https://github.com/taiki-e/pin-project/tree/master/tests/expand). It doesn't detect that the example with description is outdated, but this allows us to easily see what changes have been made to the code generated at the stage of PR.
