### ISSUE TITLE
Tracking issue for 1.0.0 release

### ISSUE THREAD

**Issue by Aaron1011** [taiki-e/pin-project#264]
Current pre-release: [1.0.0-alpha.1](https://github.com/taiki-e/pin-project/releases/tag/v1.0.0-alpha.1)

There haven't been any API changes since the `#[project]` attribute was deprecated. Since there are currently no open issues, I think it's a good time to release version 1.0.0.

Since this is a Semver-incompatible release, we could take the opportunity to remove the `#[project]`, `#[project_ref]`, and `#[project_replace]` attributes. Otherwise, I don't think any changes need to be made other than bumping the version number.

**Comment by taiki-e** [comment]
Sounds good 👍 If I remember correctly, there are basically only 3 changes required:
* remove helper attributes (remove `project*` attributes)
* remove `Replace` argument
* prevent access to projection-type if the user doesn't name it (move projection-type to inside `const _: () = {}`)

**Comment by taiki-e** [comment]
Another likely change is to remove support for rust 1.34-1.36 and remove the build-script, but I have no particular strong opinion on this.

**Comment by taiki-e** [comment]
Released [1.0.0-alpha.1](https://github.com/taiki-e/pin-project/releases/tag/v1.0.0-alpha.1). I'll wait for a few weeks and then release 1.0.0 if we don't have any big issues.

**Comment by taiki-e** [comment]
Previously, I said "we need to decide on a policy when we release 1.0" in https://github.com/taiki-e/pin-project/pull/219#issuecomment-626206397. 
I think "at least support a year ago compiler, and MSRV bump requires minor version bump" is preferable at this time.
However, I think it is unlikely that we will rely on language features that really require MSRV bump from 1.37.

**Comment by taiki-e** [comment]
FWIW, here is a list of language features/changes that I think may affect pin-project(-lite) in the future:

* `safe_packed_borrow` become a hard error (https://github.com/rust-lang/rust/issues/27060)
  The currently applied `safe_packed_borrow` becomes unknown lint and https://github.com/taiki-e/pin-project-lite/issues/26 becomes fixed. There are no code changes on pin-project(-lite) side.
* `proc_macro_def_site` stabilized (https://github.com/rust-lang/rust/issues/54724)
  We can use this via build script. (Perhaps actually proc-macro2 should handle it.)
* `trivial_bounds` stabilized (https://github.com/rust-lang/rust/issues/48214)
  The existing code is not broken, so code changes on pin-project(-lite) side are not needed.
* Implemented & stabilized RFC 2145 private in public (https://github.com/rust-lang/rust/issues/48054)
  We can use this via build script. Or the existing code is not broken, so code changes on pin-project(-lite) side are not needed.
* Implemented & stabilized RFC1598 generic associated types (https://github.com/rust-lang/rust/issues/44265)  
  We can use this via build script. Or major version bump is needed (breaking change on public API)
* Implemented & stabilized inherent associated types (https://github.com/rust-lang/rust/issues/8995)
  We can use this via build script. Or major version bump is needed (breaking change on public API)

(There are many uncertainties, so this list does not include anything like significant changes in the existing macro system, unapproved RFCs, or pre-RFCs.)
