### ISSUE TITLE
#[pin_project] panics with `internal error: entered unreachable code` when used inside a MBE with vis

### ISSUE THREAD

**Issue by WaffleLapkin** [taiki-e/pin-project#312]
On latest nightly (`1.51.0-nightly (2021-01-14 e38fb306b7f5e65cca34)`) started panicing with `internal error: entered unreachable code` message.

MRE:
```rust
#[macro_use]
macro_rules! req_future {
    ($v:vis) => {
        #[pin_project::pin_project]
        $v struct Send
        {
            #[pin]
            inner: ()
        }
    };
}

req_future! { pub }
```
[(play)](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2018&gist=9601efe2e637f136294b95bc8db75691)

**Comment by Aaron1011** [comment]
This should be fixed by https://github.com/rust-lang/rust/pull/81029

**Comment by taiki-e** [comment]
Fixed in nightly-2021-02-01. Thanks @Aaron1011 for the fix!
