### ISSUE TITLE
Rust-Analyzer compatibility

### ISSUE THREAD

**Issue by teozkr** [taiki-e/pin-project#319]
Currently, pin-project's macros aren't expanded by Rust-Analyzer, which prevents things like auto-completing into projections. This is due to pin-project using a bunch of features that Rust-Analyzer still doesn't understand. However, it doesn't look like any of these are ultimately fundamental to the way pin-project works.

- [ ] Attribute proc macros aren't expanded (https://github.com/rust-analyzer/rust-analyzer/issues/6029)
  - pin-project is already implemented as a derive macro internally, so it'd just require shifting the public API towards it (the existing `#[pin_project]` can be kept as a compatibility wrapper, so no breakage is required here)
- [X] Rust-Analyzer doesn't see "macro-private" types (that is, constructs like `const _: () = { struct __FooProjection {} };`)
  - Workaround: Named projections (`#[pin(project = FooProj)]`) are already placed in the regular outer scope
- [x] Rust-Analyzer doesn't see "macro-private" impls (`const _: () = { impl Foo {} };`
  - Put the `fn project()` impl in the regular outer scope if the projection type is renamed (and the same for `fn project_ref()`)
- [X] Rust-Analyzer doesn't infer projection type parameters (`let foo: Foo<T>; foo.project()` is inferred as `FooProj<{unknown}>`, https://github.com/rust-analyzer/rust-analyzer/issues/8100)
  - Workaround: The type is inferred correctly when called using UFCS (`let foo: Foo<T>; Foo::project(foo)` is inferred correctly as `FooProj<T>`)
  - This also happens when the impl is written manually, so this seems to be some RA bug that we can't do much about
- [x] Reexported macro can't be seen properly if also importing `#[pin_project]`
  - Workaround: Standardize on either `#[pin_project]` or `#[derive(PinProject)]` within a single module

**Comment by taiki-e** [comment]
As said in #320, the rust-analyzer team seems to be starting to work on support for attribute proc-macros (https://github.com/rust-analyzer/rust-analyzer/issues/8486), so I would prefer to wait for it instead of adding the API on the pin-project side for now.

**Comment by taiki-e** [comment]
rust-analyzer added experimental support for attribute macros: https://github.com/rust-analyzer/rust-analyzer/pull/9128

**Comment by jonas-schievink** [comment]
> * Rust-Analyzer doesn't see "macro-private" impls (`const _: () = { impl Foo {} };`

This should also work now

**Comment by Aaron1011** [comment]
Issue https://github.com/rust-analyzer/rust-analyzer/issues/6029 has been closed - is there anything left to do here?

**Comment by teozkr** [comment]
Doesn't seem to be working for me.. on https://gist.github.com/teozkr/0971d3f7d7ce0369861f167287bc5de0, Rust-Analyzer has no idea about either `WrapperProj` or `Wrapper::project` existing. This is on rust-analyzer/rust-analyzer@009e6ceb1ddcd27a9ced3bcb7d0ef823379185a1 (the current `master`).

**Comment by teozkr** [comment]
Curiously, it seems to work fine in VSCode, while Emacs completely ignores the proc macro and everything it generates. So maybe this is actually just a problem with how lsp-mode configures rust-analyzer now?

**Comment by teozkr** [comment]
Yeah, apparently I had screwed up enabling proc attr macro support in my RA. After fixing that pin-project worked just fine! So it looks like this issue can finally be closed, then.
