### ISSUE TITLE
Cannot build with RUSTFLAGS="-Zsanitizer=address"

### ISSUE THREAD

**Issue by catenacyber** [taiki-e/pin-project#327]
`cargo build` finishes ok 
```
   Compiling pin-project v1.0.7 (/rust/registry/src/github.com-1ecc6299db9ec823/pin-project-1.0.7)
    Finished dev [unoptimized + debuginfo] target(s) in 11.24s
```

But `RUSTFLAGS="-Zsanitizer=address" cargo build` errors with
```
Compiling pin-project-internal v1.0.7
   Compiling pin-project v1.0.7 (/rust/registry/src/github.com-1ecc6299db9ec823/pin-project-1.0.7)
error: /rust/registry/src/github.com-1ecc6299db9ec823/pin-project-1.0.7/target/debug/deps/libpin_project_internal-93b7f2afde7461c5.so: undefined symbol: __asan_stack_free_7
  --> src/lib.rs:82:9
   |
82 | pub use pin_project_internal::pin_project;
   |         ^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `pin-project`
```

**Comment by taiki-e** [comment]
You have to pass `--target` flag.

See also [documentation of `-Z sanitizer`](https://doc.rust-lang.org/nightly/unstable-book/compiler-flags/sanitizer.html#build-scripts-and-procedural-macros):

> ### Build scripts and procedural macros
>
> Use of sanitizers together with build scripts and procedural macros is technically possible, but in almost all cases it would be best avoided. This is especially true for procedural macros which would require an instrumented version of rustic.
>
> In more practical terms when using cargo always remember to pass --target flag, so that rustflags will not be applied to build scripts and procedural macros.

**Comment by catenacyber** [comment]
Thanks it works :-)
