### ISSUE TITLE
Ambiguous macro use does not compile

### ISSUE THREAD

**Issue by hhamana** [taiki-e/pin-project#337]
Environment: 
pin-project 1.09, with dependency on pin-project-internal 0.4.27
Windows 10. rustc 1.57.0 (f1edd0429 2021-11-29)

```
error[E0659]: `parse_quote_spanned` is ambiguous (`macro_rules` vs non-`macro_rules` from other module)
   --> \.cargo\registry\src\github.com-1ecc6299db9ec823\pin-project-internal-0.4.27\src\pin_project\derive.rs:865:67
    |
865 |                 proj_generics.make_where_clause().predicates.push(parse_quote_spanned! { span =>
    |                                                                   ^^^^^^^^^^^^^^^^^^^ ambiguous name
    |
note: `parse_quote_spanned` could refer to the macro defined here
   --> \.cargo\registry\src\github.com-1ecc6299db9ec823\pin-project-internal-0.4.27\src\utils.rs:22:1
    |
22  | / macro_rules! parse_quote_spanned {
23  | |     ($span:expr => $($tt:tt)*) => {
24  | |         syn::parse2(quote::quote_spanned!($span => $($tt)*)).unwrap_or_else(|e| panic!("{}", e))
25  | |     };
26  | | }
    | |_^
note: `parse_quote_spanned` could also refer to the macro imported here
   --> \.cargo\registry\src\github.com-1ecc6299db9ec823\pin-project-internal-0.4.27\src\pin_project\derive.rs:7:5
    |
7   |     *,
    |     ^
    = help: use `self::parse_quote_spanned` to refer to this macro unambiguously
```

**Comment by taiki-e** [comment]
This is already fixed in [0.4.29](https://github.com/taiki-e/pin-project/releases/tag/v0.4.29). See https://github.com/taiki-e/pin-project/pull/335 for more.

**Comment by hhamana** [comment]
hmm, interesting. since this came up after adding a dependency that relied on this, I assumed 0.4.27 was the latest, turns out cargo had decided to lock to that version.
`cargo update` unpinned the dependency and fetched the version with fix.
thank you~

**Comment by taiki-e** [comment]
I've reverted the increase in the minimum version of syn in pin-project 1.0.10 (because adding pin-project 1.0.9 to the dependencies was forcing syn 1.0.84+), and yanked the old versions of pin-project that did not compile with the latest syn. So the chances of users encountering this issue will be much lower.

In any case, users who run into this problem can fix this issue by updating pin-project by `cargo update`.
