### ISSUE TITLE
provide project method on `&mut Pin<&mut Self>`

### ISSUE THREAD

**Issue by ijackson** [taiki-e/pin-project#345]
AFAICT it is not possible, given a function which takes `Pin<&mut Sefl>`, to make two function calls in turn which take `Pin<&mut Self>`.  This is because the borrow checker's special logic for permitting this for `&mut Self` does not apply to `Pin<&mut Self>`.

I think it would be possible to solve this problem if `pin_project` provided something like this:
```
    fn project_mut(self: &mut Pin<&mut Self>) -> ....
```

It seems that this was previously done, but this was changed in #89.  Obviously I'm not suggesting it ought to be changed back.  But I don't see any reason why it wouldn't be sensible to provide both.  I think this should be sound because the outer `&mut` guarantees unique ownership of the inner `&mut`.

Would you welcome a MR to provide this other method, perhaps optionally?

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=a538875119bf28650f67540fe94a440f

**Comment by taiki-e** [comment]
As discussed in #89, you can use [`.as_mut()`](https://doc.rust-lang.org/nightly/std/pin/struct.Pin.html#method.as_mut) to reborrow `Pin<&mut Self>`.

```diff
-      self.project().field; // ERROR *self` moved due to this method call
+      self.as_mut().project().field;
```
```diff
- pin_ref.takes_pin();
- pin_ref.takes_pin(); // ERROR value used here after move
+ pin_ref.as_mut().takes_pin();
+ pin_ref.takes_pin();
```

https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=826520ca2b49581ce0a8d9a89a4c734e

**Comment by ijackson** [comment]
Oh.  Thank you for educating me and sorry for wasting your time!
