### ISSUE TITLE
Why was 1.0.10 yanked from crates.io?

### ISSUE THREAD

**Issue by dsherret** [taiki-e/pin-project#348]
I'm just curious why 1.0.10 was yanked from crates.io? I guess old binary crates depending on a pinned old version of pin-project will no longer build?

![image](https://user-images.githubusercontent.com/1609021/177374168-06e0fde4-55c4-40cc-9eba-8ba2b44505e7.png)

**Comment by taiki-e** [comment]
After recent compiler changes, rustc almost always emits dead code warnings for the code generated by pin-project (https://github.com/taiki-e/pin-project/pull/346).
It broke the minimal versions check of some projects, so, I have yanked old versions.

**Comment by taiki-e** [comment]
> I guess old binary crates depending on a pinned old version of pin-project will no longer build?

No, if Cargo.lock exists it builds with a warning.

**Comment by dsherret** [comment]
> > I guess old binary crates depending on a pinned old version of pin-project will no longer build?
> 
> No, if Cargo.lock exists it builds with a warning.

```rs
> cargo install deno --version 1.23.0
  Downloaded deno v1.23.0
  Downloaded 1 crate (3.3 MB) in 2.69s
    Updating crates.io index
  Installing deno v1.23.0
error: failed to compile `deno v1.23.0`, intermediate artifacts can be found at `C:\Users\david\AppData\Local\Temp\cargo-installSzOTgk`

Caused by:
  failed to select a version for the requirement `pin-project = "=1.0.10"`
  candidate versions found which didn't match: 1.0.11, 0.4.30, 0.3.5, ...
  location searched: crates.io index
  required by package `deno v1.23.0`
```

It seems to have broken them.

**Comment by taiki-e** [comment]
Can you use `--locked` flag?

**Comment by dsherret** [comment]
Yup, it works with `--locked`. That's not too bad then. I documented it. Thanks!

**Comment by taiki-e** [comment]
The reason it was yanked is for pedantic checks in some projects, so I reverted the yank for now.
