### ISSUE TITLE
Not possible to call project when struct contains associated type

### ISSUE THREAD

**Issue by jonhoo** [taiki-e/pin-project#76]
```rust
#[pin_project]
pub struct ServiceList<T> where T: IntoIterator,
{
    inner: T::IntoIter,
}
```
No `impl Unpin` is generated for this struct, so if I later write:
```rust
fn poll(
    mut self: Pin<&mut Self>,
    _: &mut Context<'_>,
) -> Poll<...> {
    match self.project().inner.next() {
```
it fails to compile with
```
error[E0596]: cannot borrow data in a dereference of `std::pin::Pin<&mut <T as std::iter::IntoIterator>::IntoIter>` as mutable
  --> tower-discover/src/list.rs:49:15
   |
49 |         match self.project().inner.next() {
   |               ^^^^^^^^^^^^^^^^^^^^ cannot borrow as mutable
   |
   = help: trait `DerefMut` is required to modify through a dereference, but it is not implemented for `std::pin::Pin<&mut <T as std::iter::IntoIterator>::IntoIter>`
```

**Comment by taiki-e** [comment]
@jonhoo Thanks for the reporting.

Unfortunately, I couldn't reproduce it.
Did you probably try to write code like this?: https://github.com/taiki-e/tower/commit/8bfbdcc80d7f1d926aab2af69f1bf72fde967b45

**Comment by jonhoo** [comment]
Ah, yes, sorry, there was an indirection through `Enumerate` which I generalized. That was indeed the change! Can you reproduce with that?

**Comment by taiki-e** [comment]
> Can you reproduce with that?

It can be compiled :)

(If you got the error from the editor, not the command line... rls may not be able to immediately reflect changes in proc-macro related code, so it may be fixed when rls is restarted.)

**Comment by jonhoo** [comment]
Ah, looks like I mistakenly added a `#[pin]` to the `inner` field. All good now!
