### ISSUE TITLE
Change the argument type of project method back to `self: Pin<&mut Self>`

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/pin-project#89]
The signature of the generated `project` method changes as follows.

before:
```rust
fn project(self: &mut Pin<&mut Self>) -> ProjectedType;
```

after:
```rust
fn project(self: Pin<&mut Self>) -> ProjectedType;
```

---

The advantage of the current approach is that you can call the `project` method multiple times without `.as_mut()`.

However, there are drawbacks such as requiring a different method to avoid lifetime issues (#65), and not being able to call the method without importing trait (https://github.com/taiki-e/pin-project/issues/21#issuecomment-530206201).

Also, by reverting this, the code generated by the macro will be simpler.

Related: https://github.com/taiki-e/pin-project/pull/47#issuecomment-530467225

PR: #90

**Comment by taiki-e** [comment]
I thought the effects of doing this.

1. the generated code is reduced by about 10-15 + number of fields/variants lines per `#[pin_project]`.

2. Since it does not depend on stabilization of `self: &mut Pin<&mut Self>` and resolves #80, blockers of 0.4 release are gone. (https://github.com/taiki-e/pin-project/issues/21#issuecomment-530206201)

3. This will not significantly increase the code that we need to write.
    * hyper: https://github.com/hyperium/hyper/compare/master...taiki-e:pin-project-next
    * tower: https://github.com/tower-rs/tower/compare/v0.3.x...taiki-e:pin-project-next

**Comment by taiki-e** [comment]
cc @Aaron1011 @Nemo157 @jonhoo @seanmonstar @LucioFranco Any thoughts on this?

**Comment by LucioFranco** [comment]
So having just released like 10 of the tower crates that depend on alpha.11, not _too_ excited about this haha.

On a real note, would it make sense to wait to see if `&mut Pin<..>` will make it into `1.39` then make a decision from there?

**Comment by taiki-e** [comment]
@LucioFranco

> On a real note, would it make sense to wait to see if `&mut Pin<..>` will make it into `1.39` then make a decision from there?

This is certainly what I thought was the most realistic a week ago. However, most of the reason why the current pin-project is unstable is about `self: &mut Pin<..>` related issues (most other issues are either backward compatible or can be implemented while keeping backward compatibility), and even if `self: &mut Pin<..>` is stable, the current complexity cannot be completely removed. So I'm not sure if it really makes sense to wait. (I am thinking of merging this and releasing beta. I believe we can stabilize the crate after making some non-breaking changes/adjustments.)

That being said, this is a fairly breaking change for existing alpha users, so I'd like to help with the update as much as possible (Specifically, I will write a few patches, but is there anything else I can do?).

**Comment by Nemo157** [comment]
In my current usage of `pin-project` (which I haven't tried updating to 0.4 yet) I also have a lot of my own `self: Pin<&mut Self>` methods. There's no way I'm going to do the same trait-indirect workaround to change these to `self: &mut Pin<&mut Self>`, so my methods are already pretty full of `self.as_mut().foo()`, so having to do it for `project()` as well isn't a big deal.

I do need the ability to return values bound to the lifetime of the input pin, switching that to be via `project_into()` wouldn't be a massive deal since they're all just `get_pin_mut` functions on wrappers, but that vs `as_mut()` feel like similarly sized downsides to me.

**Comment by RalfJung** [comment]
How widely known do you feel it is that people have to call `as_mut`? Maybe it would make sense to add a section on that to the libstd docs, so that people have a better chance of learning about this? I can help review that PR.

**Comment by LucioFranco** [comment]
> So I'm not sure if it really makes sense to wait.

Totally makes sense, I'm 👍 on board with this change then.

**Comment by taiki-e** [comment]
> How widely known do you feel it is that people have to call `as_mut`?

I'm not sure about Pin::as_mut, but in the first place, I feel that many of the convenience features related to Pin API are not well known. (Pin::set (https://github.com/tower-rs/tower/pull/323#discussion_r322239400), Option::as_pin_mut (https://github.com/tower-rs/tower/pull/316#discussion_r319770004), pin_utils::pin_mut (https://github.com/hyperium/hyper/pull/1923), etc...)

**Comment by taiki-e** [comment]
> Maybe it would make sense to add a section on that to the libstd docs, so that people have a better chance of learning about this?

> I'm not sure about Pin::as_mut, but in the first place, I feel that many of the convenience features related to Pin API are not well known.

Perhaps it is enough to add a description and an example to the method documentation. There is currently [no example](https://doc.rust-lang.org/nightly/core/pin/struct.Pin.html#method.as_mut) and there is no mention of the need to use `as_mut` in these situations.

**Comment by RalfJung** [comment]
That might be a good start, yes.

**Comment by taiki-e** [comment]
@RalfJung: I've filed https://github.com/rust-lang/rust/pull/64529

**Comment by taiki-e** [comment]
I'm going to merge this and some of the existing issues and release beta within a few days.
